# このワークフローはGitHubリリースが作成された時に実行され、
# MavenパッケージをGitHub Packagesに公開します。
name: Maven Package

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            # ソースコードをチェックアウト
            - uses: actions/checkout@v4

            # Java開発環境のセットアップ
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github
                  settings-path: ${{ github.workspace }}

            # Mavenでプロジェクトをビルド
            - name: Build with Maven
              run: |
                  echo "Mavenビルドプロセスを開始します..."
                  mvn -B package --file pom.xml
                  echo "Mavenビルドが完了しました"

            # GitHub Packagesにパッケージを公開
            - name: Publish to GitHub Packages Apache Maven
              run: |
                  echo "GitHub Packagesへの公開を開始します..."
                  mvn deploy -s $GITHUB_WORKSPACE/settings.xml
                  echo "パッケージの公開が完了しました"
              env:
                  GITHUB_TOKEN: ${{ github.token }}
